spring:
  application:
    name: team-service
server:
  port: 8094
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: squadagenda
#axon:
#  distributed:
#    enabled: true
#    jgroups:
#      bid-addr: 127.0.0.1
axon:
  amqp:
    exchange: events
  #eventhandling:
    #processors:
      #newevents:
        #source: events

logging:
  level:
    org:
      springframework:
        data: debug