spring:
  application:
    name: team-service
server:
  port: 8094
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: squadagenda

axon:
  amqp:
    exchange: events
  #eventhandling:
    #processors:
      #newevents:
        #source: events

logging:
  level:
    org:
      springframework:
        data: debug